# PANDA SERIES

In [1]:
import numpy as np
import pandas as pd

In [6]:
a1 =pd.Series([1,2,3,4,5])
print(a1)
a2 =pd.Series(['a','b','c','d','e'])
print(a2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object


In [7]:
marks=pd.Series([1,2,3],['Akash','Rahul','Guru'])
print(marks)

Akash    1
Rahul    2
Guru     3
dtype: int64


In [2]:
ser1=pd.Series([1,2,3,4,5],dtype=np.float64)
print(ser1)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64


In [5]:
import numpy as np 
import pandas as pd
i=pd.Index(["a","b","c","d","e"])
ser1=pd.Series([1,2,3,4,5],index=i)

print(ser1)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [6]:
ser1=pd.Series({"Rohit":40,"KL":23,"Virat":100,"Panth":12,"Chahal":2})
print(ser1)

Rohit      40
KL         23
Virat     100
Panth      12
Chahal      2
dtype: int64


# DATAFRAMES

DATAFRAME IS A COLLECTION OF MULTIPLE SERIES

# pd.DataFrame(array_name,index,columns)

In [7]:
import numpy as np
import pandas as pd
arr=np.arange(0,9).reshape(3,3)
print(arr)       #Numoy Array
df=pd.DataFrame(arr,index=['a','b','c'],columns=['A','B','C'])
print(df)        #Pandas DataFrame

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [8]:
df=pd.DataFrame([[19,20,18,16],[16,16,14,14],[20,12,13,15]], index=['Abhinav','Nihal','Gururaj'],columns=['OSA','PYTHON','JAVA','SE'])
print(df)

         OSA  PYTHON  JAVA  SE
Abhinav   19      20    18  16
Nihal     16      16    14  14
Gururaj   20      12    13  15


In [11]:
df=pd.DataFrame({"Osa":[23,20,19,25],"Python":[12,20,32,24],"Java":[17,20,18,18]},index=[1,2,3,4]
               )
print(df)

   Osa  Python  Java
1   23      12    17
2   20      20    20
3   19      32    18
4   25      24    18


In [12]:
#Error : All arrays must be of same lenght
df=pd.DataFrame({"Osa":[23,20,190,25],"python":[12,20,32]})
print(df)

ValueError: All arrays must be of the same length

In [13]:
import pandas as pd 
ser1=pd.Series([22,10,13])
ser2=pd.Series([17,17,18,16])
df=pd.DataFrame({"OSA":ser1,"Python":ser2})
print(df)

    OSA  Python
0  22.0      17
1  10.0      17
2  13.0      18
3   NaN      16


# CREATE DATAFRAME CONTAINING INFORMATION ABOUT CITIES

In [14]:
i=pd.Index(["Karnatka","Maharastra","Gujarat"])
#pop=pd.Series([1.2,3.0,2.0],i)
#cop=pd.Series(["Begalure","Mumbai","Gandhinagar"],i)
#df=dp.DataFrame({"population":pop,"capital":cap})
df=pd.DataFrame([["1.2","Bengalur"],["2.0","Mumbai"],["3.0","Ghandinagar"]],index=["Karnataka","Maharastara","Gujarat"],columns=["Population","capital"])
print(df)

            Population      capital
Karnataka          1.2     Bengalur
Maharastara        2.0       Mumbai
Gujarat            3.0  Ghandinagar
